stages:
  - lint
  - test
  - build

variables:
  PYTHON_VERSION: "3.10"
  DOCKER_IMAGE: flask-ci-app:latest

lint:
  stage: lint
  image: python:${PYTHON_VERSION}
  script:
    - pip install flake8
    - flake8 app tests

test:
  stage: test
  image: python:${PYTHON_VERSION}
  script:
    - pip install -r requirements.txt
    - pip install pytest
    - pytest

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE .
