name: Mirror to GitLab

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to GitLab
        env:
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_REPO_URL: ${{ secrets.GITLAB_REPO_URL }}
        run: |
          git config --global user.name "GitHub Mirror Bot"
          git config --global user.email "mirror@example.com"
          git remote add gitlab https://$GITLAB_USERNAME:$GITLAB_PASSWORD@${GITLAB_REPO_URL#https://}
          git push --force gitlab main
